name: Unit tests

on:
  push:
    branches: ['master', 'main']
  pull_request:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7.7", "3.2.2"]
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run spec tests
        run: bundle exec rake spec
      - name: Run lint tests
        run: bundle exec rake rubocop
